apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
      - name: setup-permissions
        image: laravel-app:latest
        imagePullPolicy: Never
        command: ['/bin/bash', '-c']
        args:
        - |
          mkdir -p /var/www/storage/framework/views
          mkdir -p /var/www/storage/framework/cache
          mkdir -p /var/www/storage/framework/sessions
          mkdir -p /var/www/bootstrap/cache
          chown -R www-data:www-data /var/www/storage
          chown -R www-data:www-data /var/www/bootstrap/cache
          chmod -R 775 /var/www/storage
          chmod -R 775 /var/www/bootstrap/cache
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/storage
        - name: laravel-cache
          mountPath: /var/www/bootstrap/cache
        - name: laravel-views
          mountPath: /var/www/storage/framework/views
      containers:
      - name: laravel-app
        image: laravel-app:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: laravel-config
        - secretRef:
            name: laravel-secret
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/storage
        - name: laravel-cache
          mountPath: /var/www/bootstrap/cache
        - name: laravel-views
          mountPath: /var/www/storage/framework/views
      volumes:
      - name: laravel-storage
        persistentVolumeClaim:
          claimName: laravel-storage-pvc
      - name: laravel-cache
        persistentVolumeClaim:
          claimName: laravel-cache-pvc
      - name: laravel-views
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  namespace: laravel-app
spec:
  selector:
    app: laravel-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage-pvc
  namespace: laravel-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-cache-pvc
  namespace: laravel-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
